### ISSUE TITLE
Instalacion de angular y typescript

### ISSUE THREAD

**Issue by mariogonzalezispc** [PPROF2-2022ProgWeb/g05-aula2-gestiondesposito-g05#14]
Por favor instalar estas dos extensiones (typescript y Angular) en su VCCODE , y en lo posible documentar si tuvieron problema en el proceso para facilitar a los demás integrantes del grupo.
Una vez instalado hacer pruebas de compilación de index.html, en **SU RAMA** no en el main. Hacer capturas de pantalla y colocarlas en las respuestas de esta isuue para ver el resultado. No hacer merge al proyecto.

**Comment by MonicaAntich** [comment]
Ya instale NodeJs con problemas pero me ayudo este tutorial (https://youtu.be/4N4UaFQdk9g).
Quiero instalar TypeScript y no hay manera. Me da el siguiente  error:

tsc -v : No se puede cargar el archivo C:\Users\Asus\Desktop\NodeJs\node-v16.15.1-win-x64\tsc.ps1 porque la ejecución de scripts está deshabilitada en este sistema. Para obtener más información, consulta el tema about_Execution_Policies en https:/go.microsoft.com/fwlink/?LinkID=135170.

En línea: 1 Carácter: 1   + tsc -v

Fui a San Youtube y encontre un tutorial explicando como habilitar los scripts (https://www.youtube.com/watch?v=bSe2txn_NuQ)  pero tengo miedo de dejar expuesta la seguridad de mi compu.

Lo respectivo Angular, lo instale con los pasos dados por Profe Guillen, desde visual studio code

**Comment by gastonloco** [comment]
## compilación de index.html

### Paso 1

abrir la terminal donde esta alojado el proyecto, en este caso tengo cargado con cuatro componentes para hacer una prueba, en este caso se intento hacer una copia del proyecto anterior, solo el index pero sin ningún evento solo utilice tres componente para armar la estructura Header, Contenedor1 y Footer.

![image](https://user-images.githubusercontent.com/63177312/174873423-fe604a15-ebbb-417a-b46b-c619ef5d4b63.png)

![image](https://user-images.githubusercontent.com/63177312/174873471-84ca8be5-7910-4fae-a296-8b7cacf08cae.png)

### Paso 2
Se realiza la compilación introduciendo el siguiente código mientras este este activo, se podrá visualizar la pagina.
El código a implementar es **ng serve -o** esta operación puede tardar unos minutos.

![image](https://user-images.githubusercontent.com/63177312/174873916-5c6bf8f6-c7ea-4723-bce7-99ae7f547e4f.png)


![image](https://user-images.githubusercontent.com/63177312/174874015-d283293e-0161-4247-9470-d02d73816465.png)


### Paso 3
Al agregar -o esto hace que el navegador automáticamente abra el proyecto en el **http://localhost:4200/**

![image](https://user-images.githubusercontent.com/63177312/174874244-d7ac66fe-07cd-4b1b-9d73-343d184895b1.png)

### Paso 4
Para cerrar la visualización hay que teclear en el terminal **Ctl+C**

![image](https://user-images.githubusercontent.com/63177312/174874436-a13caf2c-b910-4401-ae1a-b9f8131b7a91.png)

### Paso 5
y si actualizamos el navegador ya no tendrá conexión.

![image](https://user-images.githubusercontent.com/63177312/174874537-82d171e3-bbc1-414b-873c-3bdf7229b271.png)
