### ISSUE TITLE
Modificar aspecto de abm con JS

### ISSUE THREAD

**Issue by mariogonzalezispc** [PPROF2-2022ProgWeb/g05-aula2-gestiondesposito-g05#16]
En base al formulario completo de ABM productos hacer una rutina de JS que apague los "div" no necesarios para cada solape.

**Comment by MonicaAntich** [comment]
Resuelto

**Comment by mariogonzalezispc** [comment]
Se agrego una rutina de JS para apagar los div contenedores de cada label/input, de esta forma hacemos que el formulario se adecue para alta, baja o modificación. Falta construir rutina para la consulta y esta solo se puede hacer una vez que tengamos la conexion con la base de datos en el BACKEND
