### ISSUE TITLE
Creación de Backend con JAVA

### ISSUE THREAD

**Issue by gastonloco** [PPROF2-2022ProgWeb/g05-aula2-gestiondesposito-g05#2]
Se realizara la parte lógica para vincular el frontend con la base de datos, el soft a utilizar es JAVA.

**Comment by mariogonzalezispc** [comment]
Dia 18-06-2022 se crea base de datos 
gestion_mgalarmas 
se crea DNS en NO-IP para base de datos Mariadb
y acceso remoto
DNS marioserver1.ddns.net
user ispca2g5
pass ispca2g5
