### ISSUE TITLE
Modificar base de datos gestion_mgalarmas (tabla productos)

### ISSUE THREAD

**Issue by mariogonzalezispc** [PPROF2-2022ProgWeb/g05-aula2-gestiondesposito-g05#9]
Por favor modificar la tabla "Productos" para que contenga, 
id de producto
rubro
marca
modelo
descripción
origen
proveedor
precio de venta
precio de costo
stock
ganancia
tipo de iva

**Comment by MonicaAntich** [comment]
La tabla producto ya esta creada. Ver en archivo CreacionTablas.sql del proyecto. Revisar las otras tablas creadas
